// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
)

type Config struct {
	Key   string
	Value string
}

type User struct {
	ID           uuid.UUID
	Handle       string
	Name         string
	PasswordHash string
}

type UserRole struct {
	UserID     uuid.UUID
	Permission int64
	Access     int64
}
