// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_roles (user_id, permission, access)
VALUES (?, ?, ?)
`

type AddUserRoleParams struct {
	UserID     uuid.UUID
	Permission int64
	Access     int64
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, addUserRole, arg.UserID, arg.Permission, arg.Access)
	return err
}

const clearUserRoles = `-- name: ClearUserRoles :exec
DELETE
FROM user_roles
WHERE user_id = ?
`

func (q *Queries) ClearUserRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearUserRoles, userID)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, handle, name, password_hash)
VALUES (?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           uuid.UUID
	Handle       string
	Name         string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Handle,
		arg.Name,
		arg.PasswordHash,
	)
	return err
}

const getUserByHandle = `-- name: GetUserByHandle :one
SELECT id, handle, name, password_hash
FROM users
WHERE handle = ?
LIMIT 1
`

func (q *Queries) GetUserByHandle(ctx context.Context, handle string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByHandle, handle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Name,
		&i.PasswordHash,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, handle, name, password_hash
FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Name,
		&i.PasswordHash,
	)
	return i, err
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT permission, access
FROM user_roles
WHERE user_id = ?
`

type ListUserRolesRow struct {
	Permission int64
	Access     int64
}

func (q *Queries) ListUserRoles(ctx context.Context, userID uuid.UUID) ([]ListUserRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRolesRow
	for rows.Next() {
		var i ListUserRolesRow
		if err := rows.Scan(&i.Permission, &i.Access); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
