// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Config struct {
	Key       string
	Value     string
	UpdatedAt time.Time
}

type User struct {
	Key       string
	Value     string
	UpdatedAt time.Time
}
